name: focus_detector_v2
description: Detects when your widget appears or disappears from the screen.
publish_to: none
version: 3.1.0+1
homepage: https://github.com/irfnyas/focus_detector

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector:
    git:
      url: https://github.com/huangred/flutter.widgets.git
      ref: 042196e85ef7c886542a036c409869cfcdff638f
      path: packages/visibility_detector

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
